### ISSUE TITLE
Session class reference modified

### ISSUE THREAD

**Issue by vmitchell85** [awssat/tailwind-shift#18]
I had the following in a blade view:

`Session::get('variable')`

it was modified and left

`:get('variable')`

**Comment by abdumu** [comment]
thanks for reporting.
 could you share a the code of the affected line.

**Comment by vmitchell85** [comment]
There isn’t really much else to share... it’s was a blade file with a line with no tailwind classes on it:


Something like
```
{{Session::get(‘variable’)}}
```

I abandoned the conversion, but will try to get the actual line later today

**Comment by vmitchell85** [comment]
@abdumu EDIT: This is fixed, here was the original code though:

![image](https://user-images.githubusercontent.com/1248035/87335973-268a4a80-c50f-11ea-8024-60a7152fd0a6.png)

`<div class="alert alert-{!!Session::get('message-type', 'danger')!!}" id="errors">`

**Comment by vmitchell85** [comment]
@abdumu I was wrong... didn't have the latest pulled down... it is fixed!

Thanks a ton!
