### ISSUE TITLE
Doesn't work on SCSS/SASS

### ISSUE THREAD

**Issue by mikemand** [awssat/tailwind-shift#2]
Possibly also won't work for LESS or other pre-compiled stylesheets.

The command I ran was: `tailwind-shift resources/ --recursive=true --replace=true --extensions="vue,php,scss"`

An example snippet of code in my `_common.scss` file (I have several SASS files for different parts of the app, but `_common.scss` shares common styles and components that are then `@import`ed into the other SASS files):

```postcss
@responsive {
    .button-blue {
        @apply .bg-blue .text-white;
        &:hover {
            @apply .bg-blue-dark .text-white;
        }

        &.disabled,
        &:disabled,
        &[disabled] {
            @apply .bg-blue-lightest .text-blue-dark;
        }
    }
}
```

**Comment by mikemand** [comment]
Thanks, @abdumu! 👍

**Comment by aphofstede** [comment]
Same for LessCSS?
