### ISSUE TITLE
Grey vs gray

### ISSUE THREAD

**Issue by aphofstede** [awssat/tailwind-shift#4]
From the upgrade docs:
"For greys (note that grey has changed to gray 🇺🇸):"

The config file updates to `gray` but the string replacer replaces `text-grey` with `text-grey-500`.

Haven't tried to run my converted html yet, so maybe I'm just missing something?

**Comment by vmitchell85** [comment]
Is this possibly a still issue? Looks like the spelling wasn't changed on my run:

![image](https://user-images.githubusercontent.com/1248035/87345536-33fb0100-c51e-11ea-8540-e22a4525594b.png)

**Comment by abdumu** [comment]
We didn’t implement that.
Do you think this should be replaced here too in addition to the config file?

**Comment by vmitchell85** [comment]
If I recall correctly (I can try to do some testing later) `grey` will no longer work at all unless you added a custom `grey` color back into the config file.

I had to search for `-grey-` in my project and replace it with `-gray-` though i knew I didn't have that string anywhere except in tailwind classes.

**Comment by vmitchell85** [comment]
Thanks for all your hard work @abdumu ... really appreciate this tool you've created.
