### ISSUE TITLE
Variants keys not replaced

### ISSUE THREAD

**Issue by aphofstede** [awssat/tailwind-shift#8]
The variants config object is reconstructed, but the keys still use the old name, e.g. 
```
    variants: {
        textStyle: ['responsive', 'hover', 'focus', 'group-hover'],
    }
```
Expected:
```
    variants: {
        fontStyle: ['responsive', 'hover', 'focus', 'group-hover'],
    }
```

**Comment by aphofstede** [comment]
From the release notes upgrade guide:
"Here is a complete list of the sections that been split into multiple sections:

Old | New
-- | --
flexbox | flexDirection, flexWrap, alignItems, alignSelf, justifyContent, alignContent, flex, flexGrow, flexShrink
lists | listStylePosition, listStyleType
position | position, inset
textStyle | fontStyle, fontSmoothing, textDecoration, textTransform
whitespace | whitespace, wordBreak

Note that in some cases (position, whitespace) the original section still exists, while in others (flexbox, textStyle), the original section has been completely removed."

**Comment by abdumu** [comment]
Thanks for reporting this.
I'm pretty sure it's fixed now, but if it's still there please comment to reopen the issue.
